### ISSUE TITLE
[RFC] Prismic structure

### ISSUE THREAD

**Issue by defudef** [DivanteLtd/next#109]
Related to #103 

Folders structure:
- `packages`
  -  `commercetools`
      - `composables`
        - **usePrismic.ts**
  -  `theme`
     - `components`
         - **PrismicDocument.vue**

**UsePrismic - pseudocode**

```TS
export default ($prismic) => ({
  getDocumentByUuid: (pageType, pageUuid) => PrismicDocument // throws DocumentNotFound or similar
})
```

**PrismicDocument**

```HTML
<template>
  <div v-for="block in document">
     <div v-if="block.type === image">
        <prismic-image :field="block.data" />
     </div>
     ...and other blocks are rendered in similiar way
  </div>
</template>
```

**Example of Prismic use:**

```HTML
<template>
  <prismic-document :document="document" />
</template>
```

```Vue
<script>
export default {
  components: [
    PrismicDocument
  ],
  asyncData($prismic, error) {
    const { getDocumentByUuid } = usePrismic($prismic, error)

    return getDocumentByUuid('customPage', 'privacy-policy')
  },
}
</script>
```
Simple as that.

**Comment by filrak** [comment]
1. Prismic integration should be a separate package (if there is enough content to make it separate package, otherwise lets just keep it directly in a theme)
2. We don't use `asyncData`, you need to figure out how to use it in `setup` function
