### ISSUE TITLE
I want to use CommerceTools backend in test environment So I can play around with that during development

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/next#11]
**Context**
When we play around with API Client and later Test Site based on Storefront UI we will have to call some CommerceTools instance. We want to setup that and configure in test environment.

**Acceptance Criteria**
* Everyone in the team knows where the CommerceTools test instance is located.
* Everyone is able to login to admin panel.
* It is documented what URL and auth methos we should use to call the API.
* All the restricted information is documented in Confluence space.

**Comment by andrzejewsky** [comment]
@rmakara  I think we already have this - I have my own demo account and also we have another one from LC
