### ISSUE TITLE
Implement thank-you page

### ISSUE THREAD

**Issue by andrzejewsky** [DivanteLtd/next#140]
**Context**
In previous task we let user to proceed to the checkout. After he/she finishes the checkout process we want to get him/her back to the Thank You Page.

**Acceptance Criteria**
* After a successful checkout process user is redirected to the thank you page.
* User can see a Thank You Page.
* Content of the Thank You Page is displayed in an aesthetic way.

**Next task**
* #118 Order summary on thank you page

**Comment by rmakara** [comment]
Added description

**Comment by pspaczek** [comment]
@kulczycki, @andrzejewsky https://storybook.storefrontui.io/?path=/story/pages-thank-you--common here you can find our implementation of thank-you page.
