### ISSUE TITLE
[SPIKE] Research on Algolia

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/next#150]
- [x] How the API of Algolia looks like?
- [x] How to integrate Algolia with commercetools?
- [x] How to structurize integration of `next` with Algolia?
- [x] How Algolia stores the data? Is there some `document` node?
- [x] How to implement search with Algolia + commercetools?

**Comment by patzick** [comment]
related scope to #199

**Comment by patzick** [comment]
### How the API of Algolia looks like?

dedicated JS API Client, searching is simple and similar to ElasticSearch - [https://www.algolia.com/doc/api-reference/api-methods/search/#examples](https://www.algolia.com/doc/api-reference/api-methods/search/#examples)

### How to integrate Algolia with commercetools?

Two ways depending on needs:

1. if every request ex. for categories needs to go thru Algolia - override method inside API-client
2. if only some of them → we're creating a new composable which is using useCategoryFactory but implements different search method. This way project can have for example useCategory and useAlgoliaCategory composables with same interfaces

### How to structurize the integration of `next` with Algolia?

It could be done as a separate package, like prismic, which is implementing Next API client convention. Or it can create composables using just Algolia.

### How Algolia stores the data? Is there some `document` node?

Algolia works on indexes, similar to ElasticSearch, and result returns pagination info with search hits, example for
```js
    // with params
    index.search('query string', {
      attributesToRetrieve: ['firstname', 'lastname'],
      hitsPerPage: 50,
    }).then(({ hits }) => {
      console.log(hits);
    });
```
response could be
```json
    {
      "hits": [
        {
          "firstname": "Jimmie",
          "lastname": "Barninger",
          "objectID": "433",
          "_highlightResult": {
            "firstname": {
              "value": "&lt;em&gt;Jimmie&lt;/em&gt;",
              "matchLevel": "partial"
            },
            "lastname": {
              "value": "Barninger",
              "matchLevel": "none"
            },
            "company": {
              "value": "California &lt;em&gt;Paint&lt;/em&gt; & Wlpaper Str",
              "matchLevel": "partial"
            }
          }
        }
      ],
      "page": 0,
      "nbHits": 1,
      "nbPages": 1,
      "hitsPerPage": 20,
      "processingTimeMS": 1,
      "query": "jimmie paint",
      "params": "query=jimmie+paint&attributesToRetrieve=firstname,lastname&hitsPerPage=50"
    }
```
### How to implement search with Algolia + commercetools?

As with question `How to integrate Algolia with commercetools? ` - we can have different approaches depending on project requirements.
