### ISSUE TITLE
Extending API Client methods in override()

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/next#163]
**Context**
Within' the `override()` method we should be able to extend other methods with the same interface as the original one.

**Acceptance Criteria**
* We can overwrite API client methods from override() method.
* Tests.
* Docs.

**Comment by filrak** [comment]
Example with the API

```js
import { override } from '@vue-storefront/comemrcetools-api'

override({
 // needs to be typed!
 getProduct () {
    // new method
 }
})
```

Also we should be able to run the default version of this method via `this.super()`

```js
override({
 // needs to be typed
 getProduct () {
   return this.super()
 }
)}
```

`override` NEEDS TO BE TYPED
