### ISSUE TITLE
I want to use search to find the products So I do not have to go through categories

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/next#198]
**Context**
In most of the eCommerce systems there is a Search bar / textfield. Like in Google. :) We want to let the users start using it. Before that we need to work on its spike - https://github.com/DivanteLtd/next/issues/199 and refine the task scope / description.

**Acceptance Criteria**
To be filled after spike - https://github.com/DivanteLtd/next/issues/199

**Comment by andrzejewsky** [comment]
Acceptable criteria
- useProduct.search uses commetcetools search for fetching products when I want to search by phase
- the search bar on the top is able to search products
