### ISSUE TITLE
I want to use filters in category page So I can limit the products visible in the category page

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/next#200]
**Context**
After opening a specific category I want to use filters for narrowing the list of the products to make it easier to find the ones, that I am interested in.

**Warning**
* Filtering is usually a complex thing. Please refine it into a few smaller stories!

**Acceptance criteria**
* I can see a list of available filters for the current category.
* I can filter by ... PLEASE LIST IT BEFORE STARTING THE TASK.
* When I use a filter then products list gets updated.
* I can use a few filters at once (OR / AND logic).

**Comment by ghost** [comment]
TODO @Qrzy 

Have to click Done to apply filters on category page 
| 
In order for filters to be applied, we must press 'Done' however this is not visible, you have to scroll to find it. - your filter options are ticked and so I can imagine people would assume they're applied and click the X to exit filters without actually applying them
-- | --

**Comment by Qrzy** [comment]
The problem mentioned above is already fixed in new SFUI design and example pages so it will be applied here too.
