### ISSUE TITLE
I want to use sorting in the category page so I can change the order of the products to find these easily

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/next#201]
**Context**
After opening a specific category I want to sort the products in the products list to make it easier for me to find an interesting product. 

**Acceptance criteria**
* I can see a list of available properties, that I can sort by for the current category.
* I can sort by:
  * name,
  * price.
* When I use a sorting feature then products list gets updated.
* I can sort ascending.
* I can sort descending.

**Comment by ghost** [comment]
TODO

Dropdowns do not look clickable 
| 
There is a dropdown to change the sorting option on category pages, at least on Chrome/Mac there is no indication that you can change this sorting, and the cursor does not change to a hand when hovering on it either. Same for 'items per page' at the bottom of categories. Also an issue on product pages for size and option selection dropdowns
-- | --
