### ISSUE TITLE
I want to see CMS content and image in Mega Menu

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/next#210]
**Context**
In #209 we delivered the mega menu. Now we want to let the administrator customize its look by adding images and CMS content.

**Blocked by:**
* #209 

**Acceptance Criteria**
* I can define custom text, which is visible in mega menu.
* I can define an image, which is visible in mega menu.

**Comment by filrak** [comment]
Shouldn't this be part of lovecrafts theme, not ours?

**Comment by ghost** [comment]
Agreed with @rmakara to close this.
