### ISSUE TITLE
SSR breaks when used conditionally

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/next#232]
if `search` (or any other method using persisted state) is used conditionally it always shows the content from initial SSR (then it gets error on CSR therefore uses old content). 

Especially on category page it completely breaks it because if you change the category products are still the same.

**In console:**

```
Uncaught (in promise) Error: [vue-composition-api] "onServerPrefetch" get called outside of "setup()"
```

**Examples of code causing error**

```js
  // Category.vue
    const { categories, search, loading } = useCategory('category-page');
    const { products: categoryProducts, search: productsSearch } = useProduct('category-products');

    search({ slug: lastSlug });

    // ugly workaround until we will have async setup
    watch(categories, () => {
      if (categories.value.length) productsSearch({ catId: categories.value[0].id });
    });
```
```js
  // RelatedProducts.vue
    if (categories.length > 0) {
      search({ catId: [categories[0]] });
    }
```
I disabled SSR for product for now.

**Comment by andrzejewsky** [comment]
I've implemented a new API that fixes conditional async calls in here: https://github.com/DivanteLtd/next/pull/277 but it's worth to wait for Vue 3 release as it introduces async setup that could solve our problem, so let's keep it as it is, if async setup won't work, we use this one.
