### ISSUE TITLE
Add API Extractor

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/next#233]
To have a clear view of breaking changes after each release we should incorporate [API Extractor](https://api-extractor.com/) into our build process.

- It should generate the report based on API changes from `{plaform}/api-client/index.ts` and `{platform}/composables/index.ts`. 

- The report should be generated in a root of integration as `api.json` (eg `commercetools/api.json`)

- Generation should happen each time we run a build command for each package/platform (probably you will need to pass args to cli to determine which package you want to create report from)

For reference:
- what `shopware-pwa` team did (that one is in markdown), you can check their repo for some inspiration https://github.com/DivanteLtd/shopware-pwa/tree/master/api

Next steps -> use data from API Extractor for docs ;)

**Comment by I2olanD** [comment]
https://github.com/DivanteLtd/next/pull/235
