### ISSUE TITLE
Pagination breaks SSR

### ISSUE THREAD

**Issue by andrzejewsky** [DivanteLtd/next#298]
![Screenshot 2020-03-26 at 15 51 17](https://user-images.githubusercontent.com/7943292/77660523-ba90d000-6f79-11ea-91b1-4a5312512615.png)

+ transition error

**Comment by Qrzy** [comment]
The transition error is fixed now, it was due to the usage of `SfLoader`.

But I didn't notice the SSR problem in the load of prop type mismatch warns, I will look at it asap.
