### ISSUE TITLE
Public Roadmap?

### ISSUE THREAD

**Issue by nkmnz** [DivanteLtd/next#324]
Hi! I'm very happy to see that you're working on integrating Nuxt into vue-storefront! Is there a public roadmap? I'd love to contribute. I have my own usecase for a storefront in my nuxt application, though I haven't worked with typescript yet...

**Comment by filrak** [comment]
Hey! About which integration you're talking? All of them have separate roadmaps. If its just VSF Next its ready to be integrated with basically anything now
