### ISSUE TITLE
Make locale resolving more flexible

### ISSUE THREAD

**Issue by lukeromanowicz** [DivanteLtd/next#349]
Currently, core-theme forces using cookies for storing locale settings. There should be a possibility to easily use different locale resolvers e.g. local storage/path/host based.

**Comment by filrak** [comment]
You mean only theme or core itself? if the theme - it will stay like that since we're using nuxt-i18n module.  If someone wants to use different driver he/she can just remove the module and use something else. 

If that applies to the core then you're right, please clarify

**Comment by lukeromanowicz** [comment]
Yes, it's about the theme.
