### ISSUE TITLE
No header on mobile

### ISSUE THREAD

**Issue by andrzejewsky** [DivanteLtd/next#369]

**Comment by ghost** [comment]
ToDo:

No header on mobile
Below 1024px, there is no header available to browse etc

**Comment by pspaczek** [comment]
@kulczycki, @andrzejewsky before 0.7.2 we had a bug with media. Now everything should be ok on 1024px

**Comment by pspaczek** [comment]
but probably you talking on search, categories etc. we work on improve it to SFUI
![Zrzut ekranu 2020-04-27 o 09 12 26](https://user-images.githubusercontent.com/12138170/80344067-46db2f00-8867-11ea-8004-65be5326cd08.png)

**Comment by pspaczek** [comment]
@kulczycki @andrzejewsky in Storefront UI we add $ and language selector but categories shout by on SfMegaMenu -> https://www.figma.com/file/N0Ct95cSAoODNv7zYS01ng/Storefront-UI-Design-System?node-id=3226%3A14554
![categories](https://user-images.githubusercontent.com/12138170/80498887-8dff1800-896c-11ea-96a4-6ccf636b0751.png)
here -> https://github.com/DivanteLtd/next/issues/369#issuecomment-619781005 you saw just alternative mobile categories, but I recomended SfMegaMenu

**Comment by ghost** [comment]
Marcin B will work on this today that relates to this issue.  https://github.com/DivanteLtd/storefront-ui/issues/1139

**Comment by pspaczek** [comment]
@kulczycki at SfUI 0.7.10 you can find an example for Language Selector https://storybook.storefrontui.io/?path=/story/molecules-bottommodal--example-language-selector and implement it in aside slot (visible on mobile) https://storybook.storefrontui.io/?path=/story/molecules-bottommodal--example-language-selector
if you need search use `sf-header--has-mobile-search`. relates -> https://github.com/DivanteLtd/next/issues/367
