### ISSUE TITLE
Pagination client side only

### ISSUE THREAD

**Issue by ghost** [DivanteLtd/next#387]
Pagination client side only
Server side pagination not working, buttons with onclick handlers

**Comment by Qrzy** [comment]
This one is being handled by SFUI team, here is their a11y audit result and all listed actions required:
https://github.com/DivanteLtd/storefront-ui/issues/960

**Comment by pspaczek** [comment]
related https://github.com/DivanteLtd/storefront-ui/pull/1073/commits/0ef26500f9f47eaacaf7450c0418a18a9da1d517

**Comment by Qrzy** [comment]
Here we need to pass URL to the pagination component - it already uses links instead of buttons.

**Comment by pspaczek** [comment]
fixed at SfUI 0.7.8
