### ISSUE TITLE
Accessibility issue during navigation/pagination

### ISSUE THREAD

**Issue by ghost** [DivanteLtd/next#388]
Accessibility issue during navigation/pagination
No accouncement of changed content or change of focus, this applies to page navigation, pagination and features such as filtering.

**Comment by Qrzy** [comment]
Reported to SFUI team: https://github.com/DivanteLtd/storefront-ui/issues/1058

**Comment by pspaczek** [comment]
@Qrzy, @kulczycki now you should saw a focus
