### ISSUE TITLE
Tab accessibility: product details

### ISSUE THREAD

**Issue by ghost** [DivanteLtd/next#392]
When I enter the size/option dropdowns on the PDP using space bar I am getting inconsisten results, sometimes it reads out all of the options in the menu at once and it's a lot of speaking. I cannot click enter when on the add to cart button to submit the form. Also cannot tab through the 'Save for Later', 'Add to compare',  'Description', 'Read Reviews' and 'Additional information' sections

**Comment by Qrzy** [comment]
This is covered by latest a11y audit done by SFUI team: https://github.com/DivanteLtd/storefront-ui/issues/960
We're waiting for a new version fixing this accessibility issue.

**Comment by pspaczek** [comment]
@Qrzy, @kulczycki if we talking about the Product page you should improve it on your project. 
1. ad. "Enter", you should use <form> and @submit on your project.
2. ad. tabs, it should be fixed, please check https://storybook.storefrontui.io/?path=/story/pages-product--common
