### ISSUE TITLE
Tab accessibility: category

### ISSUE THREAD

**Issue by ghost** [DivanteLtd/next#394]
Tabbing works for the first set of filters, but once you go past e.g. t-shirts on this page https://vsf-next-demo.storefrontcloud.io/c/men/men-clothing-jackets then the focus box disappears. You also don't seem able to select all elements in the header and footer using tab

**Comment by Qrzy** [comment]
This is covered by latest a11y audit done by SFUI team: https://github.com/DivanteLtd/storefront-ui/issues/960
We're waiting for a new version fixing this accessibility issue.

**Comment by pspaczek** [comment]
@kulczycki will be fixed at SFUI 0.7.6 
fix for tab on product list -> https://github.com/DivanteLtd/storefront-ui/pull/1132
