### ISSUE TITLE
No accordian menu on category landing page on mobile/tablet screen

### ISSUE THREAD

**Issue by ghost** [DivanteLtd/next#395]
I cannot see the accordian menu that exist on desktop.

**Comment by Qrzy** [comment]
Will be applied once new design will be implemented in SFUI storybook:
https://github.com/DivanteLtd/storefront-ui/issues/1062

**Comment by pspaczek** [comment]
IMO you should move categories and sort by into filter SfSidebar, by I asked the designer about it. You can do it without SFUI team support. When the designer gives me a response I will update these issues.

**Comment by pspaczek** [comment]
@kulczycki you should move categories to filters sidebar on mobile

https://www.figma.com/file/N0Ct95cSAoODNv7zYS01ng/Storefront-UI-Design-System?node-id=263%3A573 
![Zrzut ekranu 2020-05-4 o 11 52 57](https://user-images.githubusercontent.com/12138170/80954546-e0718600-8dfd-11ea-8569-c40329d79cf8.png)

**Comment by Qrzy** [comment]
I will do this right after #200
