### ISSUE TITLE
Images dont load if javascript is disabled

### ISSUE THREAD

**Issue by ghost** [DivanteLtd/next#398]
Crawlers (other than google) wont be able correctly index tthe images

**Comment by Qrzy** [comment]
Reported to SFUI team: https://github.com/DivanteLtd/storefront-ui/issues/1066

**Comment by pspaczek** [comment]
@kulczycki sorry for our delay, these issues need my attention and I will fix it on this week. But when we fixed it on SFUI then you should just update SFUI to next version

**Comment by pspaczek** [comment]
@kulczycki @Qrzy fixed at SfUI 0.7.7
PR -> https://github.com/DivanteLtd/storefront-ui/pull/1150
