### ISSUE TITLE
Accessibility of link/action names

### ISSUE THREAD

**Issue by ghost** [DivanteLtd/next#401]
button/action names have the same name eg `<button aria-label="Add to wishlist">` this will result in confusion as to which product they are adding to the wishlist

**Comment by Qrzy** [comment]
reported to SFUI team: https://github.com/DivanteLtd/storefront-ui/issues/960#issuecomment-614530782

**Comment by pspaczek** [comment]
@kulczycki @Qrzy fixed, please check and confirm
