### ISSUE TITLE
My VSF next commerce tools installation does not work after changing the connection strings to my own CT project

### ISSUE THREAD

**Issue by adnansaleemsandhila** [DivanteLtd/next#421]
Hi

My VSF next commerce tools installation does not work after changing the connection strings to my own CT project. following are the steps to reproduce
- I setup VSF Next for CT
- I created an API client in my mc.commercetools.com and did select the appropriate project scopes
- I changed my connection strings in /packages/commercetools/theme/plugins/commercetools-config.js as per following screen shot
![image](https://user-images.githubusercontent.com/15811720/80484888-e5ec4d80-8971-11ea-9994-68aa1520502a.png)
- but no luck and it does give me an error as per following screenshots
![image](https://user-images.githubusercontent.com/15811720/80485201-690da380-8972-11ea-9a49-f07765a59090.png)
![image](https://user-images.githubusercontent.com/15811720/80485296-8b9fbc80-8972-11ea-85c8-7adbbee60e8a.png)
can anybody please let me know how can i successfully connect it to my own CT project? 
Please note: I am using the next branch in main VSF repo instead of separate next repo (that i am posting this issue on) to setup my project. 
Thank you

**Comment by andrzejewsky** [comment]
First of all, I think, there is wrong URI: it should be something like `https://api.commercetools.com/[project]/graphql`, the one you used is probably for rest API. Also, `authHost` should be set to`https://auth.sphere.io`. Please make sure if you set the right permissions in your MC,  and if it still doesn't work, please text me on community slack

**Comment by adnansaleemsandhila** [comment]
Hi @andrze Thank you for following that for me, but it did not work though error did get changed i.e as per following screenshot

![image](https://user-images.githubusercontent.com/15811720/80516235-9a9b6480-899c-11ea-85b9-2b2336a2c07d.png)

**Comment by andrzejewsky** [comment]
Hey, look at the docs: https://docs.commercetools.com/graphql-api it says:

```
You can access the GraphQL endpoint with following URL:
https://api.{region}.{cloudProvider}.commercetools.com/{projectKey}/graphql
```

so you have  to add `/nestosh/graphql` and the end of API uri

**Comment by adnansaleemsandhila** [comment]
Hi @andrzejewsky It did work after changing my graphQL end point, Thank you
