### ISSUE TITLE
The cart icon is not accessible

### ISSUE THREAD

**Issue by andrzejewsky** [DivanteLtd/next#424]
I can focus cart icon but I can't open the cart using a keyboard
<img width="362" alt="Screenshot 2020-04-30 at 11 54 12" src="https://user-images.githubusercontent.com/7943292/80697535-624d7080-8ad9-11ea-8179-17983fa94af1.png">

**Comment by pspaczek** [comment]
@andrzejewsky will be fixed at SFUI 0.7.6
fix for header icons a11y - use by keyboard -> https://github.com/DivanteLtd/storefront-ui/pull/1143
