### ISSUE TITLE
Implement helpers for reading specific data from the api response

### ISSUE THREAD

**Issue by andrzejewsky** [DivanteLtd/next#48]
Acceptable criteria:
- getGallery(product: Product)
- getName(product: Product)
- getPrice(product: Product)
- getSlug(product: Product)
- getVariants(product: Product)

**Comment by filrak** [comment]
We can have multiple helpers for multiple entities (cms content, product category) so we should have prefixes: `getPrice` -> `getProductPrice` etc. Also i have few suggestions:
`getGallery` -> maybe `getProductImages` is better? I suppose it will also include thumbnail which is not a part of gallery.

@patzick we will need your 2 cents here as well ;)

**Comment by patzick** [comment]
great, I will put comments on each separately and let you input how we have it now. It's great time to make them common!
I will soon help with core interfaces for helpers, and then it will also be easier to discuss them.
For sure we need to discuss more like each separately than all at once :)

### getGallery
currently, we have `getProductMediaGallery`. Agree with @filrak that `getProductImages` sounds better
* input -> Product (T)
* output  -> `UiMediaGalleryItem[]` (name to change)
```ts
export interface UiMediaGalleryItemUrl {
  url: string;
}
export interface UiMediaGalleryItem {
  small: UiMediaGalleryItemUrl;
  normal: UiMediaGalleryItemUrl;
  big: UiMediaGalleryItemUrl;
}
```

### getName
would move basically every getter to be with the corresponding item name, so:
`-> getProductName`
* input -> Product (T)
* output  -> string

### getPrice
we have different prices, so following UI, we should have two:
* `getProductRegularPrice`
* `getProductSpecialPrice`

* input -> Product (T)
* output  -> number

### getSlug
not all platforms have slug, I would go for `getProductId`, or `getProductUniqueId`, or something similar

* input -> Product (T)
* output  -> string

### getVariants
-> `getProductVariants`
* input -> Product (T)
* output  -> Product[] (T)
i'm not sure about this one, output may be something else potentially, Shopware for example has same structure for Variants as for parent product.

and also with this we need 
### `isProductSimple`
* input -> Product (T)
* output  -> boolean

**Comment by filrak** [comment]
I agree with everything except
- last one `isProductSimple` -> it's platform specific I believe, correct me if I'm wrong
- prices, I think we should have a single helper for prices instead of a separate one for every one of them, we should aim for minimal set of helpers

**Comment by patzick** [comment]
@filrak thanks, so for these exceptions

##### helpers
if Product Variants are not platform-specific than this helper is 100% legit, maybe naming is just unfortunate ;D
could be `isParentProduct(product)` or `isProductVariant(product)` for consistency

##### pricing 
for pricing, I agree and disagree at the same time ;D

we could appropriately pack helpers, in the documentation have will promote easiest ones, but have an ability to use them all like
`import {getProductPrices} from 'platformPackage/helpers'` // this would return grouping helper
`import {productHelpers} from 'platformPackage/helpers'` // this is set of product helpers

this approach would give the ability to just use a specific helper and help with those edge cases like need to override specific helper (I know it's not a common case, but it could happen; of course it would need to keep the same API)

**Comment by EugeneHlushko** [comment]
Hi guys, just a random question in regard of the `getXPrice` methods, when\where would taxation be handled? Is it something that you expect the platform to do?

**Comment by patzick** [comment]
Hey @EugeneHlushko, yeah. Prices should come from platform. There are a lot of rules, not only taxes but current promotions, stock changes, number of items in cart etc.
Sure, this helpers would allow also to calculate the price based on product attributes, but it is always better to have prices from the platform and reduce possibility of different prices error.
