### ISSUE TITLE
I want to display Category Tree in Category Page So I know the real structure of the categories in eCommerce

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/next#55]
**Context**
As now we are able to fetch the products from the single category we want to start going towards displaying the category tree and making it usable for the user. In the scope of that task we want to populate Storefront UI Accordion component with real categories from commercetools.

Accordion is handling only level 0 and level 1 categories. We do not want to display deeper categories on that stage.

**Dependencies**
* https://storybook.storefrontui.io/?path=/story/organisms-accordion--basic

**Acceptance Criteria**
* Accordion component from Storefront UI is being used.
* Categories of level 0 are fetched from commercetools.
* Categories of level 1 are fetched from commercetools.
* I can expand and collapse level 0 categories.
* I can see level 1 categories after expanding level 0 category.
* All the categories (level 0 and 1), that we get from the API are displayed.
* If API returns `not-active` or `not-visible` categories then we do not display these in the Accordion.

**Not in the scope**
* Displaying categories of levels 2 and deeper.
* Redirections / links to categories.

**Next tasks**
* #56 Redirect to categories

**Comment by EugeneHlushko** [comment]
Hi @rmakara 
Do you think "If API returns not-active or not-visible categories then we do not display these in the Accordion." should be done on UI level? Maybe add this to the graphql query instead to reduce the response size and keep this business logic outside of ui?

**Comment by rmakara** [comment]
Yes, exactly. That shouldn't be handled as additional logic in the presentation layer. In the scope of that task we may check how commercetools API works in that case and answer the following questions:

1. Do we get inactive categories from the commercetools API with some flag or we do not get these at all?
2. Do we get invisible categories from the commercetools API with some flag or we do not get these at all?

The best scenario is to skip these products in the API layer.

However, if we get these not-so-useful categories in the responses then we might extract that scope of skipping these categories to separate issues. And as you recommended it is better to implement it layer below.

The idea for that AC was to simply direct attention to that aspect.
