### ISSUE TITLE
Add missing elements on header

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/next#67]
1. Add different mobile content for header -> different logo and currency select component
![image](https://user-images.githubusercontent.com/15185752/71158830-dda63800-2244-11ea-88e1-c3671818653f.png)
2. Add "marketing bar" visible only on desktop (`SfTopBar")
![image](https://user-images.githubusercontent.com/15185752/71158921-11815d80-2245-11ea-8054-b2a49cb6d792.png)

**Comment by rmakara** [comment]
Task blocked due to planned Storefront UI changes with the header. Deleting from the current board.
