### ISSUE TITLE
Create initial repository structure

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/next#8]
**Context**
After 2-3 years of development od Vue Storefront 1, we came up with some thoughts about new Next architecture. We want to prepare the repository with its initial structure.

**Acceptance Criteria**
* Directory structure in repo is created.
* It is accepted by both: Patryk and Filip.

**Comment by filrak** [comment]
Initial structure is done except tests:
https://github.com/DivanteLtd/next/issues/10
